AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation-EC2

Parameters:
  KEYname:
    Type: String
    Default: CFec2

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KEYname
      ImageId: ami-0a211f4f633a3af5f
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue pub1ao
          GroupSet:
            - !ImportValue EC2SG
      Monitoring: false
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
      IamInstanceProfile: !ImportValue Ims3

      Tags:
        - Key: Name
          Value: EC2ins
