AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation-EC2

Parameters:
  KEYname:
    Type: String
    Default: kyua5/12

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KEYname
      ImageId: ami-0a211f4f633a3af5f
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue subnet-public-1a
          GroupSet:
            -  !ImportValue securitygroup-ec2
      Monitoring: false
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
        sudo amazon-linux-extras install ansible2 -y
      #IamInstanceProfile: !ImportValue  s3-role

      Tags:
        - Key: Name
          Value: ansible-control-node


EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KEYname
      ImageId: ami-0a211f4f633a3af5f
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue subnet-public-1a
          GroupSet:
            - !Ref SecurityGroupAnsible
      Monitoring: false
      UserData: !Base64 |
        #!/bin/bash
        sudo yum update -y
        # ターゲットノード用の設定（必要に応じて追加）
      IamInstanceProfile: !ImportValue s3-role
      Tags:
        - Key: Name
          Value: ansible-target-node         
