AWSTemplateFormatVersion: 2010-09-09
Description: CF-RDS

Parameters:
  RDSMasterUser:
    Description: "RDS Master User Name"
    Type: String
    MinLength: 1
    MaxLength: 128
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  RDSUserPass:
    NoEcho: true
    Description: "RDS Master User Password"
    Type: String
    MinLength: 8
    MaxLength: 128
    AllowedPattern: "[a-zA-Z0-9]*"

Resources:
  Rds:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      AvailabilityZone: "ap-northeast-1a"
      BackupRetentionPeriod: 1
      DBSubnetGroupName: !Ref DBSubnet
      Engine: mysql
      EngineVersion: "8.0.35"
      MasterUsername: !Ref RDSMasterUser
      MasterUserPassword: !Ref RDSUserPass
      DeletionProtection: false
      DeleteAutomatedBackups: true
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      VPCSecurityGroups:
        - !ImportValue RDSSG
      Tags:
        - Key: Name
          Value: Rdsin


  DBSubnet:
   Type: AWS::RDS::DBSubnetGroup
   Properties:
    DBSubnetGroupDescription: db
    SubnetIds:
      - !ImportValue pri1ao
      - !ImportValue pri1co
    Tags:
      - Key: Name
        Value: Dbsub
