AWSTemplateFormatVersion: 2010-09-09
Description: IAM-CF
Resources:
  s3cfRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  S3InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref s3cfRole

Outputs:
  RoleS3:
    Description: S3Role
    Value: !Ref S3InstanceProfile
    Export:
      Name: Ims3
